-- MySQL Script generated by MySQL Workbench
-- Thu May  5 12:28:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exchange
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exchange
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exchange` DEFAULT CHARACTER SET utf8 ;
USE `exchange` ;

-- -----------------------------------------------------
-- Table `exchange`.`usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange`.`usr` (
  `idusr` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange`.`cryptocurrency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange`.`cryptocurrency` (
  `idcryp` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcryp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange`.`order` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `idusr` INT NOT NULL,
  `idcryp` INT NOT NULL,
  `sum` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `usr_idx` (`idusr` ASC) VISIBLE,
  INDEX `cryptocur_idx` (`idcryp` ASC) VISIBLE,
  CONSTRAINT `usr`
    FOREIGN KEY (`idusr`)
    REFERENCES `exchange`.`usr` (`idusr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cryptocur`
    FOREIGN KEY (`idcryp`)
    REFERENCES `exchange`.`cryptocurrency` (`idcryp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
